const SHOW_MODAL = "SHOW_MODAL";
const HIDE_MODAL = "HIDE_MODAL";
const MOUNT_COLORS = "MOUNT_COLORS";
const SET_DATA_LOADED_STATE = "SET_DATA_LOADED_STATE";

export {
    SHOW_MODAL,
    HIDE_MODAL,
    MOUNT_COLORS,
    SET_DATA_LOADED_STATE
}